include: package:extra_pedantic/analysis_options.yaml

linter:
  rules:
    # switch these two
    prefer_single_quotes: false
    prefer_double_quotes: true

    constant_identifier_names: false
    non_constant_identifier_names: false
    prefer_interpolation_to_compose_strings: false

    # eventually remove these
    parameter_assignments: false

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    todo: ignore
    unused_local_variable: ignore
